num=input("enter your number\n")
num1=int(num)
print("Table of : " + num)
print(num1*1)
print(num1*2)
print(num1*3)
print(num1*4)
print(num1*5)
print(num1*6)
print(num1*7)
print(num1*8)
print(num1*9)
print(num1*10)
